version: '3.2'

services:

  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: "enquete"
    ports:
      - ${DB_PORT}:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
